name: Update PFAS dataset

on:
  schedule:
    - cron: "0 3 * * *"   # tous les jours 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # nécessaire pour pousser le commit

jobs:
  build-pfas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (in source/)
        working-directory: source
        run: npm ci

      - name: Build PFAS JSON (runs from source/)
        working-directory: source
        run: npm run build:pfas

      - name: Show result
        run: ls -lh public | cat

      - name: Upload pfas.json as artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: pfas.json
          path: public/pfas.json

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/pfas.json
            git commit -m "chore: update pfas.json (auto)"
            git push
          else
            echo "No changes to commit."
          fi
